apiVersion: v1
data:
  .dockerconfigjson: "{{ template "deployment.imagePullSecret" . }}"
kind: Secret
metadata:
  name: registry-creds
  namespace: {{ .Values.namespace }}
type: kubernetes.io/dockerconfigjson
