{{- if  .Values.registry.ingress.enabled }}
{{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    {{- if .Values.registry.ingress.https.enabled }}
    cert-manager.io/cluster-issuer: {{ .Values.registry.ingress.https.issuer }}
    kubernetes.io/tls-acme: {{ quote .Values.registry.ingress.https.enabled }}
    {{- end }}
  name: {{ .Values.registry.app_name }}-ingress
  namespace: {{ .Values.namespace }}
spec:
  rules:
  - host: {{ .Values.registry.app_name }}.{{ .Values.schema.app_name }}.{{ .Values.domain }}
    http:
      paths:
      - backend:
          service:
            name: {{ .Values.registry.app_name }}-svc
            port:
              number: 5000
        path: /
        pathType: Prefix
  {{- if .Values.registry.ingress.https.enabled }}
  tls:
  - hosts:
    - {{ .Values.registry.app_name }}.{{ .Values.schema.app_name }}.{{ .Values.domain }}
    secretName: {{ .Values.registry.app_name }}-ingress-secret
  {{- end }}
{{- else if .Capabilities.APIVersions.Has "route.openshift.io/v1/Route" -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.registry.app_name }}-ingress
spec:
  host: {{ .Values.registry.app_name }}-{{ .Values.schema.app_name }}.{{ .Values.domain }}
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: {{ .Values.registry.app_name }}-svc
    weight: 100
  wildcardPolicy: None
status:
  ingress: []
{{- end }}
{{- end }}
