{{- if  .Values.registry.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    {{- if .Values.registry.ingress.https.enabled }}
    cert-manager.io/cluster-issuer: {{ .Values.registry.ingress.https.issuer }}
    kubernetes.io/tls-acme: {{ quote .Values.registry.ingress.https.enabled}}
    {{- end }}
  name: {{ .Values.registry.app_name }}-ingress
  namespace: {{ .Values.namespace }}
spec:
  rules:
  - host: {{ .Values.registry.app_name }}.{{ .Values.schema.app_name }}.{{ .Values.domain }}
    http:
      paths:
      - backend:
          service:
            name: {{ .Values.registry.app_name }}-svc
            port:
              number: 5000
        path: /
        pathType: Prefix
  {{- if .Values.registry.ingress.https.enabled }}
  tls:
  - hosts:
    - {{ .Values.registry.app_name }}.{{ .Values.domain }}
    secretName: {{ .Values.registry.app_name }}-ingress-secret
  {{- end }}
{{- end }}