apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.schema.app_name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.schema.deployment.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.schema.app_name }}
  template:
    metadata:
      labels:
        app: {{ .Values.schema.app_name }}
    spec:
      serviceAccountName: {{ .Values.schema.app_name }}-kubectl
      containers:
      - image: {{ .Values.schema.deployment.image }}
        name: schema
        env:
          - name: CLUSTER_ENDPOINT
            value: {{ .Values.schema.deployment.cluster_endpoint }}
        volumeMounts:
          - mountPath: /data
            name: schema-volume
          - name: schema-config
            mountPath: /app/web/schema/config/db.php
            subPath: db.php
          - name: schema-config
            mountPath: /app/web/schema/config/params.php
            subPath: params.php
          - name: schema-config
            mountPath: /app/web/schema/scheduler_files/configuration.json
            subPath: configuration.json
      volumes:
        - name: schema-volume
          persistentVolumeClaim:
            claimName: {{ .Values.schema.volume.name }}
        - name: configuration
          configMap:
            defaultMode: 420
            items:
              - key: configuration.json
                path: configuration.json
              - key: db.php
                path: db.php
              - key: params.php
                path: params.php
            name: configuration
      restartPolicy: Always
      imagePullSecrets:
        - name: schema-regcreds
