apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.schema.app_name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.schema.deployment.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.schema.app_name }}
  template:
    metadata:
      labels:
        app: {{ .Values.schema.app_name }}
    spec:
      serviceAccountName: {{ .Values.schema.app_name }}-kubectl
      containers:
      - image: {{ .Values.schema.deployment.image }}
        name: schema
        env:
          - name: CLUSTER_ENDPOINT
            value: {{ .Values.schema.deployment.cluster_endpoint }}
        volumeMounts:
          - mountPath: /data
            name: {{ .Values.schema.volume.name }}
          - name: schema-config
            mountPath: /app/web/schema/config/db.php
            subPath: db.php
          {{ if .Values.auth_db.enabled }}
          - name: schema-config
            mountPath: /app/web/schema/config/db2.php
            subPath: db2.php
          {{ end }}
          - name: schema-config
            mountPath: /app/web/schema/config/params.php
            subPath: params.php
          - name: schema-config
            mountPath: /app/web/schema/scheduler_files/configuration.json
            subPath: configuration.json
          {{ if .Values.auth_db.enabled }}
          - name: schema-config
            mountPath: /app/web/schema/views/user/login.php
            subPath: user.php
          {{ end }}
      volumes:
        - name: {{.Values.schema.volume.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.schema.volume.name }}
        - name: schema-config
          secret:
            defaultMode: 420
            items:
              - key: configuration.json
                path: configuration.json
              - key: db.php
                path: db.php
              {{ if .Values.auth_db.enabled }}
              - key: db2.php
                path: db2.php
              {{ end }}
              - key: params.php
                path: params.php
              {{ if .Values.auth_db.enabled }}
              - key: user.php
                path: user.php
              {{ end }}
            secretName: schema-config
      restartPolicy: Always
      imagePullSecrets:
        - name: schema-regcreds
