{{- if .Values.schema.volume.deploy_volume }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.schema.volume.name }}
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: {{ .Values.schema.volume.storageClass }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.schema.volume.size }}
{{- end }}