apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.schema.app_name }}-kubectl

---

{{ if .Values.schema.deployment.cluster }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: modify-pods-and-jobs
  namespace: {{ .Values.namespace }}
rules:
  - apiGroups: ["","batch"]
    resources:
      - pods
      - jobs
      - pods/log
    verbs:
      - create
      - get
      - list
      - delete
      - view
  - apiGroups: ["metrics.k8s.io"]
    resources:
      - pods
      - nodes
    verbs:
      - top
      - get 
      - list
{{ end }}
---

{{ if .Values.schema.deployment.cluster }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.schema.app_name }}-role
  namespace: {{ .Values.namespace }}
subjects:
- kind: ServiceAccount
  namespace: {{ .Values.namespace }}
  name: {{ .Values.schema.app_name }}-kubectl
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: modify-pods-and-jobs
  apiGroup: rbac.authorization.k8s.io
{{ end }}