apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.schema.app_name }}
  name: {{ .Values.schema.app_name }}-svc
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
    {{- if eq .Values.schema.service.type "NodePort" }}
    nodePort: {{ .Values.schema.service.nodePort }}
    {{- end}}
  selector:
    app: {{ .Values.schema.app_name }}
  type: {{ .Values.schema.service.type }}
