---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.minio.app_name }}-s3
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.minio.app_name }}
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.minio.app_name }}-console
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.minio.app_name }}
  ports:
    - protocol: TCP
      port: 9001
      targetPort: 9001