name: Test

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation. 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [closed]

env:
  IMAGE_NAME: diwis/schema


jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Test build
        run: docker-compose up -d
      - name: Test api
        shell: bash
        run: bash test-call.bash
      - name: End test
        run: docker-compose down